# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """$time$directory$git_branch$git_status$cmd_duration$memory_usage$character"""

[directory]
style = "blue bold"
truncation_length = 3

[git_branch]
symbol = ""
style = "purple"

[git_status]
style = "red"

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "took [$duration]($style) "

[memory_usage]
disabled = false
threshold = -1
symbol = "🐏"
style = "yellow bold"
format = "[$symbol$ram]($style) "

[time]
disabled = false
style = "cyan bold"
format = "[$time]($style) "
time_format = "%I:%M:%S %p"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
